<a href="https://colab.research.google.com/github/srinivasan-ES/ML/blob/main/Matrix_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
multi_array = np.array([(1,2,3,4,5),(6,7,8,9,10)])


In [6]:
print(multi_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
matrix_arr = np.ones((3,3),dtype='int')

In [17]:
print(matrix_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
matrix_arr = np.zeros((3,3),dtype='int')

In [19]:
print(matrix_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
matrix_arr = np.eye((3),dtype='int')

In [23]:
print(matrix_arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [24]:
# addition

In [30]:
array_1 = np.array([(1,2,3,4),(5,6,7,8)])

In [31]:
array_2 = np.array([(12,13,14,15),(16,17,18,19)])

In [35]:
array_3 = np.add(array_1 ,array_2)

In [36]:
print(array_3)

[[13 15 17 19]
 [21 23 25 27]]


In [37]:
array_3 = np.subtract(array_1 ,array_2)

In [38]:
print(array_3)

[[-11 -11 -11 -11]
 [-11 -11 -11 -11]]


In [39]:
x = 2* array_1
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]
